In [2]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import sklearn
import random
import tensorflow as tf
from os_elm import OS_ELM
import tqdm

In [3]:
datasets = ['CM1','JM1','KC1','KC3','KC4','MC1','MC2','MW1','PC1','PC2','PC3','PC4','PC5']
d = {}
df = pd.DataFrame(columns = ["Project","Number of Defective instances","Total Number of instances","Percentage of Defective Instances"]
)
#df.columns = ["Project","Number of Defective instances","Total Number of instances","Percentage of Defective Instances"]

for i in range(len(datasets)):
    d[i] = pd.read_csv("data/"+datasets[i]+".csv")
    try:
        df.loc[len(df)] = [datasets[i],sum(d[i][d[i].columns[-1]] == "Y"),d[i].shape[0],sum(d[i][d[i].columns[-1]] == "Y")/d[i].shape[0] * 100]
        print(datasets[i],sum(d[i][d[i].columns[-1]] == "Y"),d[i].shape[0],sum(d[i][d[i].columns[-1]] == "Y")/d[i].shape[0] * 100)
    except:
        continue

CM1 42 344 12.209302325581394
JM1 1759 9591 18.340110520279428
KC1 325 2095 15.513126491646778
KC3 36 200 18.0
MC1 68 8737 0.7782991873640838
MC2 44 125 35.199999999999996
MW1 27 263 10.26615969581749
PC1 61 735 8.299319727891156
PC2 16 1493 1.0716677829872738
PC3 138 1099 12.556869881710647
PC4 178 1379 12.907904278462654
PC5 502 16962 2.9595566560547106


In [4]:
df

Project Number of Defective instances Total Number of instances  \
0      CM1                            42                       344   
1      JM1                          1759                      9591   
2      KC1                           325                      2095   
3      KC3                            36                       200   
4      MC1                            68                      8737   
5      MC2                            44                       125   
6      MW1                            27                       263   
7      PC1                            61                       735   
8      PC2                            16                      1493   
9      PC3                           138                      1099   
10     PC4                           178                      1379   
11     PC5                           502                     16962   

    Percentage of Defective Instances  
0                           12.209302  
1                           18.340111  
2                           15.513126  
3                           18.000000  
4                            0.778299  
5                           35.200000  
6                           10.266160  
7                            8.299320  
8                            1.071668  
9                           12.556870  
10                          12.907904  
11                           2.959557

In [5]:
PC5 = d[12]
PC4 = d[11]
JM1 = d[1]

In [6]:
PC4['Defective'] = (PC4['Defective'] == "Y")*1
PC4.dtypes

LOC_BLANK                            int64
BRANCH_COUNT                         int64
CALL_PAIRS                           int64
LOC_CODE_AND_COMMENT                 int64
LOC_COMMENTS                         int64
CONDITION_COUNT                      int64
CYCLOMATIC_COMPLEXITY                int64
CYCLOMATIC_DENSITY                 float64
DECISION_COUNT                       int64
DECISION_DENSITY                   float64
DESIGN_COMPLEXITY                    int64
DESIGN_DENSITY                     float64
EDGE_COUNT                           int64
ESSENTIAL_COMPLEXITY                 int64
ESSENTIAL_DENSITY                  float64
LOC_EXECUTABLE                       int64
PARAMETER_COUNT                      int64
HALSTEAD_CONTENT                   float64
HALSTEAD_DIFFICULTY                float64
HALSTEAD_EFFORT                    float64
HALSTEAD_ERROR_EST                 float64
HALSTEAD_LENGTH                      int64
HALSTEAD_LEVEL                     float64
HALSTEAD_PR

In [7]:
X = PC4[PC4.columns[:-1]]
y = PC4[PC4.columns[-1]]
yo = y.copy()

X = (X-X.mean())/X.std()
X.describe()

LOC_BLANK  BRANCH_COUNT    CALL_PAIRS  LOC_CODE_AND_COMMENT  \
count  1.379000e+03  1.379000e+03  1.379000e+03          1.379000e+03   
mean  -1.679424e-16 -1.581202e-16  1.052256e-16         -1.227042e-15   
std    1.000000e+00  1.000000e+00  1.000000e+00          1.000000e+00   
min   -7.376029e-01 -6.559890e-01 -8.154636e-01         -4.089595e-01   
25%   -6.373511e-01 -6.559890e-01 -4.650353e-01         -4.089595e-01   
50%   -3.365958e-01 -2.732883e-01 -4.650353e-01         -4.089595e-01   
75%    2.649147e-01  1.094124e-01  2.358212e-01         -4.156200e-02   
max    8.285056e+00  1.292989e+01  7.594815e+00          1.208255e+01   

       LOC_COMMENTS  CONDITION_COUNT  CYCLOMATIC_COMPLEXITY  \
count  1.379000e+03     1.379000e+03           1.379000e+03   
mean  -1.898409e-16    -5.158230e-16           8.252202e-17   
std    1.000000e+00     1.000000e+00           1.000000e+00   
min   -5.289664e-01    -5.567631e-01          -6.451747e-01   
25%   -5.289664e-01    -5.567631e-01          -6.451747e-01   
50%   -4.254697e-01    -5.567631e-01          -2.804705e-01   
75%    9.201373e-02     5.733513e-02           8.423372e-02   
max    7.543775e+00     8.501186e+00           1.248418e+01   

       CYCLOMATIC_DENSITY  DECISION_COUNT  DECISION_DENSITY  ...  \
count        1.379000e+03    1.379000e+03      1.379000e+03  ...   
mean         2.898334e-18    6.966468e-16      5.772516e-17  ...   
std          1.000000e+00    1.000000e+00      1.000000e+00  ...   
min         -1.430837e+00   -5.707811e-01     -9.389322e-01  ...   
25%         -6.848729e-01   -5.707811e-01     -9.389322e-01  ...   
50%         -2.372947e-01   -5.707811e-01     -9.389322e-01  ...   
75%          4.589381e-01    1.211812e-01      8.323593e-01  ...   
max          3.542255e+00    8.078748e+00      3.489296e+00  ...   

       MULTIPLE_CONDITION_COUNT    NODE_COUNT  \
count              1.379000e+03  1.379000e+03   
mean              -2.982064e-16 -1.489422e-17   
std                1.000000e+00  1.000000e+00   
min               -5.357240e-01 -6.942747e-01   
25%               -5.357240e-01 -5.360260e-01   
50%               -5.357240e-01 -2.722781e-01   
75%                4.770218e-02  1.497185e-01   
max                1.171623e+01  1.428660e+01   

       NORMALIZED_CYLOMATIC_COMPLEXITY  NUM_OPERANDS  NUM_OPERATORS  \
count                     1.379000e+03  1.379000e+03   1.379000e+03   
mean                      2.407228e-16  9.473930e-17   2.592399e-17   
std                       1.000000e+00  1.000000e+00   1.000000e+00   
min                      -1.024888e+00 -5.529072e-01  -6.325653e-01   
25%                      -5.734919e-01 -4.285166e-01  -4.748065e-01   
50%                      -2.913696e-01 -2.764837e-01  -2.874679e-01   
75%                       2.164506e-01  6.904575e-02   1.167890e-01   
max                       4.617559e+00  1.883820e+01   1.600113e+01   

       NUM_UNIQUE_OPERANDS  NUM_UNIQUE_OPERATORS  NUMBER_OF_LINES  \
count         1.379000e+03          1.379000e+03     1.379000e+03   
mean         -2.547314e-16         -1.078824e-16     1.852519e-16   
std           1.000000e+00          1.000000e+00     1.000000e+00   
min          -6.536946e-01         -1.954849e+00    -8.017939e-01   
25%          -3.658923e-01         -6.775513e-01    -5.615962e-01   
50%          -2.219911e-01         -1.985647e-01    -3.650708e-01   
75%           1.617453e-01          5.997464e-01     2.245055e-01   
max           2.817450e+01          4.112315e+00     1.286764e+01   

       PERCENT_COMMENTS     LOC_TOTAL  
count      1.379000e+03  1.379000e+03  
mean      -1.779094e-15 -3.703025e-16  
std        1.000000e+00  1.000000e+00  
min       -8.619863e-01 -8.461845e-01  
25%       -8.619863e-01 -5.705292e-01  
50%       -3.529046e-01 -3.736325e-01  
75%        6.301336e-01  2.170575e-01  
max        3.494479e+00  7.423476e+00  

[8 rows x 37 columns]

In [8]:
from sklearn.decomposition import PCA

pca = PCA(n_components=10)
XT = pca.fit_transform(X)
pca.explained_variance_ratio_*100

array([44.45323967, 11.95419553,  9.27769965,  5.35220998,  4.56140915,
        4.19499958,  3.55462455,  2.88734001,  2.31394962,  1.91315073])

In [9]:
df = pd.DataFrame()
for i in range(pca.explained_variance_ratio_.shape[0]):
    df["pc%i" % (i+1)] = XT[:,i]
df.head()

pc1       pc2       pc3       pc4       pc5       pc6       pc7  \
0  3.144432 -2.302698 -0.893383 -1.106093 -0.887246  2.117540  0.807773   
1 -2.415338  0.686656 -0.762650 -1.030445  0.534131 -0.146050 -0.493515   
2 -1.542967 -0.218857 -0.824510 -0.649177 -0.594101  0.479492 -0.000753   
3 -1.418571 -0.387407 -1.194695 -0.928401 -0.364667  0.433958 -0.030997   
4 -3.250346  0.909308 -0.256969 -0.290182  0.837059  0.228297 -0.585175   

        pc8       pc9      pc10  
0 -0.141937  0.028357 -0.109380  
1 -0.242132  0.808454 -0.557148  
2 -0.410261  0.831414 -0.265180  
3  0.112860  0.731866  0.046821  
4 -0.931161  0.464159 -0.181317

In [14]:
sum(y == [1])

array([178])

In [11]:
X.shape

(1379, 10)

In [140]:
def softmax(a):
    c = np.max(a, axis=-1).reshape(-1, 1)
    exp_a = np.exp(a - c)
    sum_exp_a = np.sum(exp_a, axis=-1).reshape(-1, 1)
    return exp_a / sum_exp_a

In [57]:
tf.reset_default_graph()

In [60]:
from sklearn.model_selection import KFold
n_input_nodes = 10
n_hidden_nodes = 64
n_output_nodes = 1
kf = KFold(n_splits=5)
os_elm1 = OS_ELM(
    # the number of input nodes.
    n_input_nodes=n_input_nodes,
    # the number of hidden nodes.
    n_hidden_nodes=n_hidden_nodes,
    # the number of output nodes.
    n_output_nodes=n_output_nodes,
    # loss function.
    # the default value is 'mean_squared_error'.
    # for the other functions, we support
    # 'mean_absolute_error', 'categorical_crossentropy', and 'binary_crossentropy'.
    loss='binary_crossentropy',
    # activation function applied to the hidden nodes.
    # the default value is 'sigmoid'.
    # for the other functions, we support 'linear' and 'tanh'.
    # NOTE: OS-ELM can apply an activation function only to the hidden nodes.
    activation='tanh',
)

n_classes = n_output_nodes
for train,test in kf.split(X):
    Xtrain,Xtest = X.values[train],X.values[test]
    ytrain,ytest = y[train],y[test]
    border = int(3*len(Xtrain)/4)
    Xtrain_init = Xtrain[:border]
    Xtrain_seq = Xtrain[border:]
    ytrain_init = ytrain[:border]
    ytrain_seq = ytrain[border:]
    os_elm1.init_train(Xtrain_init, ytrain_init)
    batch_size = 64
    for i in range(0, len(Xtrain_seq), batch_size):
        x_batch = Xtrain_seq[i:i+batch_size]
        t_batch = ytrain_seq[i:i+batch_size]
        os_elm1.seq_train(x_batch, t_batch)
    for i in np.arange(0.5,1,0.1):
        y_ = os_elm1.predict(Xtest)
        pred = (y_>i)*1
        print("Threshold:",i,"F1-score:",f1_score(ytest,pred))
        print("==================")
    tf.reset_default_graph()

ValueError: Variable is_finished_init_train already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/home/parm_khakhar/Research/software-defect-prediction/Second/os_elm.py", line 50, in __init__
    initializer=tf.constant_initializer(False),
  File "<ipython-input-58-b839f77b0742>", line 22, in <module>
    activation='tanh',
  File "/home/parm_khakhar/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)


In [45]:
# Initial training phase
pbar = tqdm.tqdm(total=len(Xtrain), desc='initial training phase')
os_elm1.init_train(Xtrain_init, ytrain_init)
pbar.update(n=len(Xtrain_init))

initial training phase:   0%|          | 0/965 [00:00<?, ?it/s]

In [46]:
# the sequential training phase
pbar.set_description('sequential training phase')
batch_size = 64
for i in range(0, len(Xtrain_seq), batch_size):
    x_batch = Xtrain_seq[i:i+batch_size]
    t_batch = ytrain_seq[i:i+batch_size]
    os_elm1.seq_train(x_batch, t_batch)
    pbar.update(n=len(x_batch))
pbar.close()

sequential training phase: 100%|██████████| 965/965 [00:02<00:00, 368.03it/s]


In [47]:
y_ = os_elm1.predict(Xtest)

In [48]:
(y_ > 0.5)*1

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [53]:
for i in np.arange(0.5,0.6,0.01):
    pred = (e>i)*1
    print("Threshold:",i,"F1-score:",f1_score(ytest,pred))
    print("==================")

Threshold: 0.5 F1-score: 0.3315508021390375
Threshold: 0.51 F1-score: 0.3974358974358974
Threshold: 0.52 F1-score: 0.43773584905660384
Threshold: 0.53 F1-score: 0.4587155963302752
Threshold: 0.54 F1-score: 0.4831460674157303
Threshold: 0.55 F1-score: 0.47058823529411764
Threshold: 0.56 F1-score: 0.4409448818897637
Threshold: 0.5700000000000001 F1-score: 0.4426229508196722
Threshold: 0.5800000000000001 F1-score: 0.3818181818181817
Threshold: 0.5900000000000001 F1-score: 0.34343434343434337


In [55]:
from sklearn.metrics import f1_score,precision_score,recall_score,accuracy_score,balanced_accuracy_score, confusion_matrix
e = 1/(1+np.exp(-1*y_))
for i in np.arange(0.5,0.7,0.01):
    pred = (e>i)*1
    print("Threshold:",i,"F1-score:",f1_score(ytest,pred))
    print("Balanced-Accuracy:",balanced_accuracy_score(ytest,pred))
    print("Recall:",recall_score(ytest,pred))
    print("Precision:",precision_score(ytest,pred))
    print("Confusion-Matrix:",confusion_matrix(ytest,pred))
    print()

Threshold: 0.5 F1-score: 0.3315508021390375
Balanced-Accuracy: 0.6300892857142857
Recall: 0.96875
Precision: 0.2
Confusion-Matrix: [[102 248]
 [  2  62]]

Threshold: 0.51 F1-score: 0.3974358974358974
Balanced-Accuracy: 0.7186607142857143
Recall: 0.96875
Precision: 0.25
Confusion-Matrix: [[164 186]
 [  2  62]]

Threshold: 0.52 F1-score: 0.43773584905660384
Balanced-Accuracy: 0.7488392857142857
Recall: 0.90625
Precision: 0.2885572139303483
Confusion-Matrix: [[207 143]
 [  6  58]]

Threshold: 0.53 F1-score: 0.4587155963302752
Balanced-Accuracy: 0.7420535714285714
Recall: 0.78125
Precision: 0.3246753246753247
Confusion-Matrix: [[246 104]
 [ 14  50]]

Threshold: 0.54 F1-score: 0.4831460674157303
Balanced-Accuracy: 0.7345089285714286
Recall: 0.671875
Precision: 0.37719298245614036
Confusion-Matrix: [[279  71]
 [ 21  43]]

Threshold: 0.55 F1-score: 0.47058823529411764
Balanced-Accuracy: 0.7055357142857143
Recall: 0.5625
Precision: 0.4044943820224719
Confusion-Matrix: [[297  53]
 [ 28  36]]

T

In [158]:
from sklearn.metrics import recall_score,balanced_accuracy_score,accuracy_score,confusion_matrix,precision_score
print("Recall:",recall_score(ytest,y_pred))
print("Balanced-Accuracy:",balanced_accuracy_score(ytest,y_pred))
print("Confusion Matrix:",confusion_matrix(ytest,y_pred))
print("Accuracy:",accuracy_score(ytest,y_pred))
print("Precision:",precision_score(ytest,y_pred))

Recall: 0.9387755102040817
Balanced-Accuracy: 0.6214425496225888
Confusion Matrix: [[111 254]
 [  3  46]]
Accuracy: 0.37922705314009664
Precision: 0.15333333333333332


In [157]:
sum(ytest==1)

array([49])

In [128]:
y

array([[ 3.15751076e-01],
       [ 1.27071142e-01],
       [ 2.35016912e-01],
       [ 8.40137005e-02],
       [-1.17602408e-01],
       [ 1.55105710e-01],
       [ 2.56535172e-01],
       [-1.19824052e-01],
       [ 7.24927187e-02],
       [ 1.67057395e-01],
       [ 2.31752872e-01],
       [ 1.65274143e-01],
       [ 2.74306476e-01],
       [-3.70313525e-02],
       [-4.61696386e-02],
       [ 3.33353758e-01],
       [ 5.45381904e-02],
       [-5.24196327e-02],
       [ 2.09439397e-02],
       [ 7.41005242e-02],
       [ 3.59623909e-01],
       [ 2.11462975e-01],
       [-7.94490278e-02],
       [ 2.83737183e-02],
       [ 1.72451288e-01],
       [ 1.52432919e-02],
       [ 2.56439626e-01],
       [ 5.52012563e-01],
       [-3.70313525e-02],
       [ 9.50366259e-02],
       [ 3.98791373e-01],
       [-3.02001685e-01],
       [-3.70313525e-02],
       [ 3.01965058e-01],
       [ 4.51936305e-01],
       [ 3.31748128e-02],
       [ 1.68029785e-01],
       [ 2.09327459e-01],
       [ 1.5

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],